### ISSUE TITLE
Collect Status Mails

### ISSUE THREAD

**Issue by 3wille** [freifunkhamburg/ffffng#26]
Status Mails to the same receiver at the same time should be bundled into one mail. So you get only one mail for several nodes using the same uplink.

**Comment by baldo** [comment]
Interesting thought, though I'm not sure how to properly bundle those. There are quite some questions that arise:

1. In what time frame do two notifications have to be, so that they will be aggregated?
2. How many mails do we send over time (and in what intervals) depending on the possible combinations of nodes going online / offline? How should the logic be?
3. Are nodes mentioned more than 3 times in different mails?
4. How will the unsubscribe logic work out for those notifications?

I have a feeling that the effort required could be huge in comparison to what we would gain.

**Comment by baldo** [comment]
Closing for now as I don't feel it's worth the effort.
