### ISSUE TITLE
Migration of nodes

### ISSUE THREAD

**Issue by patrikherrscher** [freifunkhamburg/ffffng#47]
Hi,

is there any possibility to migrate the existing fastd key files to this tool? The keyfiles only contains the key and the name of the node. 

Thanks for your help

**Comment by baldo** [comment]
Hi there,

first of all, I would discourage from using ffffng as long as node information like name, gps coordinates, etc. are already being stored on the nodes. The reason is that ffffng stores those information centralized which is in my opinion is desirable for Freifunk. So if you have those information already stored decentralized (on the nodes), then I would suggest looking into solutions that keep the decentralization intact.

That being said it _could_ be possible to migrate those fastd files. The challenge would be to generate a token for each node and sending it to the owner (to allow editing the node data). You would also have to migrate other information (like email adresses, node names, coordinates, ...). Also you must have the MAC address for each node and would need to modify your Freifunk map setup to use the ffffng data (there is currently no solution for hopglass I am aware of).
